# Generated by Django 4.2.16 on 2024-11-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_categorie_nom_alter_publication_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='lien',
            field=models.URLField(default='https://example.com'),
        ),
    ]
